---
- hosts: all
  connection: local
  name: Chassis Inventory
  gather_facts: False
 # vars:
  #  ansible_python_interpreter: "/usr/bin/python3"

  tasks:

  - name: Get default inventory information
    redfish_info:
      category: "all"
      command: "all"
      baseuri: "192.168.1.199"
      username: "admin"
      password: "admin1234!"
    register: result

  - debug:
      msg: "{{ result.redfish_facts | to_nice_json }}"

