---
- hosts: all
  connection: local
  name: Chassis Inventory
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:

  - name: Get default inventory information
    redfish_info:
      baseuri: "172.16.1.210:5000"
      username: "root"
      password: "password123456"
    register: result

  - debug:
      msg: "{{ result.redfish_facts | to_nice_json }}"

