---
- hosts: all
  connection: local
  name: Chassis Inventory
  gather_facts: False

  vars:
    datatype: ChassisInventory

  tasks:

  - name: Get chassis Inventory
    redfish_info:
      category: Chassis
      command: GetChassisInventory
      baseuri: "172.16.1.210"
      username: "root"
      password: "password123456"
    register: result

  - name: Copy results to output file
    debug:
      msg: "{{ result | to_nice_json }}"
