---
- hosts: all
  connection: local
  name: Full inventory
  gather_facts: False

  tasks:

  - name: Get default inventory information
    redfish_info:
      category: Systems
      command: all
      baseuri: "192.168.1.200"
      username: "redfish"
      password: "password123"
      timeout: 120
    register: result

  - name: Write to file
    copy:
      content: '{{ result.redfish_facts | to_nice_json }}'
      dest: /Users/jmcleroy/Documents/sos/ilo4_systems.txt

#  delegate_to: localhost
#  - debug:
#      msg: "{{ result.redfish_facts }}"

