---
- hosts: all
  connection: local
  name: Chassis Inventory
  gather_facts: False
  vars:
    ansible_python_interpreter: "/usr/bin/python36"

  tasks:

  - name: Get chassis Inventory
    redfish_info:
      category: all
      command: all
      baseuri: "172.16.1.210:5000"
      username: "root"
      password: "password123456"
    register: result

  - name: Copy results to output file
    debug:
      msg: "{{ result.redfish_facts | to_nice_json }}"
