---
- name: Gather Server Info
  hosts: all
  gather_facts: false

  tasks:
    - name: Get all information available in all categories
      redfish_info:
        category: all
        command: all
        baseuri: "http://172.16.1.210:5000/"
        username: "root"
        password: "password123456"
      register: result

    - debug:
        msg: "{{ result.redfish_facts | to_nice_json }}"